# Generated by Django 4.1.3 on 2022-12-03 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Event ID')),
                ('event_title', models.CharField(max_length=50, verbose_name='Event Title')),
                ('event_description', models.CharField(max_length=256, verbose_name='Event Description')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('creator_first_name', models.CharField(max_length=30, verbose_name='Event Creator First Name')),
                ('creator_last_name', models.CharField(max_length=30, verbose_name='Event Creator Last Name')),
                ('event_email', models.CharField(max_length=100, verbose_name='Event Email')),
                ('event_phone', models.IntegerField(verbose_name='Event Phone Number')),
                ('event_city', models.CharField(max_length=100, verbose_name='Event Location: City')),
                ('event_state', models.CharField(max_length=100, verbose_name='Event Location: State')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('user_username', models.CharField(max_length=50, verbose_name='Username')),
                ('user_password', models.CharField(max_length=50, verbose_name='Password')),
                ('user_fname', models.CharField(max_length=50, verbose_name='First Namen')),
                ('user_lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('user_phone', models.IntegerField(verbose_name='Phone Number')),
                ('user_hobbies', models.JSONField(verbose_name='Hobbies')),
                ('user_interests', models.JSONField(verbose_name='Interests')),
                ('user_email', models.CharField(max_length=100, verbose_name='Email')),
                ('user_age', models.IntegerField(verbose_name='Age')),
                ('user_gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other'), ('4', 'Decline to Answer')], max_length=25, verbose_name='Gender')),
                ('user_city', models.CharField(max_length=100, verbose_name='Location: City')),
                ('user_state', models.CharField(max_length=100, verbose_name='Location: State')),
                ('user_admin', models.BooleanField(verbose_name='Is Admin')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('rsvp_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='RSVP ID')),
                ('rsvp_date', models.DateField(verbose_name='RSVP Date')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_finder.event', verbose_name='Event ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_finder.users', verbose_name='Event ID')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_finder.users', verbose_name='Event ID'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Comment ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_finder.event', verbose_name='Event ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_finder.users', verbose_name='Event ID')),
            ],
        ),
    ]
