# Generated by Django 4.1.3 on 2022-12-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_finder', '0003_comment_comment_string_alter_comment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_flagged',
            field=models.BooleanField(default=False, verbose_name='Flagged for Abuse'),
            preserve_default=False,
        ),
    ]
