# Generated by Django 4.1.3 on 2022-12-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_finder', '0004_event_event_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_phone',
            field=models.CharField(max_length=25, verbose_name='Event Phone Number'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_phone',
            field=models.CharField(max_length=25, verbose_name='Phone Number'),
        ),
    ]
